name: CI
on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: maven
      - name: Build & test
        run: mvn -B -DskipITs=false verify
      - name: Qodana
        uses: JetBrains/qodana-action@v2024.2
        with:
          cache-default-branch-only: true
